services:
  ml-service:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile_ml_service
    ports:
      - "${ML_SERVICE_PORT}:${ML_SERVICE_PORT}"
    volumes:
      - ./models:/models
    hostname: ml_service

  prometheus:
    image: prom/prometheus
    env_file:
      - ./.env
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    hostname: prometheus

  grafana:
    image: grafana/grafana
    env_file:
    - ./.env
    ports:
    - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
    - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
