global:
  scrape_interval: 15s
  scrape_timeout: 10s


scrape_configs:
  - job_name: 'scrapping-ml-service'

    metrics_path: /metrics
    scheme: http

    static_configs:
    - targets:
      - ml_service:8081